In [258]:
import pandas as pd
import json
import os
import numpy as np

In [259]:
df = pd.read_json("lagos_sale_raw_20251117_174452.json")
df.sample(n=2, random_state=42)

                               property_title          price                                        description                                           location size_sqm                                        listing_url  bedrooms  bathrooms furnishing_status  agent_name  contact                                        image_links                               property_description property_type listing_date last_updated prize_per_sqm source listing_type
1801  5bdrm Duplex in Ajah, Olokonla for sale 220,000,000.00  5bedroom beautiful classic fully detached with...           Lagos, Ajah, Olokonla, 2 days ago7 views      200  https://jiji.ng/olokonla/houses-apartments-for...         5          5       Unfurnished       Lagos  Unknown  https://pictures-nigeria.jijistatic.net/186436...  Subtype Detached Property Address not far from...        Duplex   2 days ago   2 days ago     1100000.0   jiji         sale
1190   4bdrm Duplex in Lekki Phase 2 for sale 180,000,000.00  - Modern Luxury Appurtenances\n- Spacious Livi...  PromotedLagos, Lekki, Lekki Phase 2, 3 hours a...      450  https://jiji.ng/lekki-phase-2/houses-apartment...         4          5    Semi-Furnished  Enterprise  Unknown  https://pictures-nigeria.jijistatic.net/186357...  Subtype Detached Property Address 2nd Toll Gat...        Duplex  3 hours ago  3 hours ago      400000.0   jiji         sale

## GENERAL CHECK

In [261]:
# checking for duplicates

df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2995    False
2996    False
2997    False
2998    False
2999    False
Length: 3000, dtype: bool

In [262]:
# checking for missing numbers

df.isnull().sum()

property_title          0
price                   0
description             0
location                0
size_sqm                0
listing_url             0
bedrooms                0
bathrooms               0
furnishing_status       0
agent_name              0
contact                 0
image_links             0
property_description    0
property_type           0
listing_date            0
last_updated            0
prize_per_sqm           0
source                  0
listing_type            0
dtype: int64

In [263]:
# Checking columns and their data types

df.dtypes

property_title           object
price                   float64
description              object
location                 object
size_sqm                 object
listing_url              object
bedrooms                  int64
bathrooms                 int64
furnishing_status        object
agent_name               object
contact                  object
image_links              object
property_description     object
property_type            object
listing_date             object
last_updated             object
prize_per_sqm            object
source                   object
listing_type             object
dtype: object

In [264]:
# Identifying the shape of the data

shape = df.shape
print(f"sales jiji property has column: {shape[1]} and row: {shape[0]:,}")

sales jiji property has column: 19 and row: 3,000

# COLUMN CHECKS, CLEANING, CONVERSION TO RIGHT DATA TYPE E.T.C

In [266]:
# adding commas to my displays for better readability as well

pd.options.display.float_format = '{:,.2f}'.format

## LISTING_URL

In [268]:
# checking for missing values using the unique identifier (listing url)

missing_listing_url = df['listing_url'].isnull().sum()
missing_listing_url

0

In [269]:
# checking for duplicates

print("\n" + "="*60)
print("Checking duplicates by listing_url")
print("="*60)

before = len(df)
print(f"Listings before deduplication: {before:,}")

# Count how many exact duplicate URLs exist
dup_urls = df['listing_url'].duplicated().sum()
print(f"Exact duplicate URLs found: {dup_urls}")

============================================================
Checking duplicates by listing_url
============================================================
Listings before deduplication: 3,000
Exact duplicate URLs found: 0

In [270]:
# final detailed checking for duplicates

if df['listing_url'].duplicated().any():
    print("Warning: Still have duplicates!")
else:
    print("Perfect – All listing_url are now unique")

Perfect – All listing_url are now unique

## PRICE

In [272]:
# checking for missing values

missing_price = df['price'].isnull().sum()
missing_price

0

In [273]:
# removing white spaces

df['price'] = df['price'].astype(str).str.strip()
df['price']

0       23936072470.0
1         450000000.0
2          75000000.0
3          75000000.0
4         100000000.0
            ...
2995     1700000000.0
2996      300000000.0
2997      400000000.0
2998      500000000.0
2999       85000000.0
Name: price, Length: 3000, dtype: object

In [274]:
df['price'].unique()

array(['23936072470.0', '450000000.0', '75000000.0', '100000000.0',
       '250000000.0', '10000000000.0', '330000000.0', '140000000.0',
       '270000000.0', '750000000.0', '35000000.0', '580000000.0',
       '55000000.0', '150000000.0', '175000000.0', '350000000.0',
       '2280000000.0', '3000000000.0', '480000000.0', '760000000.0',
       '2500000000.0', '180000000.0', '1700000000.0', '220000000.0',
       '300000000.0', '215000000.0', '360000000.0', '135000000.0',
       '165000000.0', '430000000.0', '280000000.0', '8000000000.0',
       '80000000.0', '160000000.0', '260000000.0', '162500000.0',
       '200000000.0', '90000000.0', '1300000000.0', '650000000.0',
       '400000000.0', '88000000.0', '285000000.0', '700000000.0',
       '370000000.0', '1400000000.0', '5300000000.0', '170000000.0',
       '10200000.0', '290000000.0', '600000000.0', '95000000.0',
       '252000000.0', '130000000.0', '85000000.0', '879000000.0',
       '790000000.0', '680000000.0', '24000000.0', '60000000.0',
       '500000000.0', '305000000.0', '390000000.0', '1200000000.0',
       '245000000.0', '900000000.0', '110000000.0', '36000000.0',
       '1500000000.0', '550000000.0', '2400000000.0', '410000000.0',
       '230000000.0', '5600000000.0', '70000000.0', '240000000.0',
       '120000000.0', '210000000.0', '730000000.0', '980000000.0',
       '1100000000.0', '190000000.0', '3.58900000337e+18', '2350000000.0',
       '43000000.0', '10000000.0', '12000000.0', '5000000000.0',
       '440000000.0', '660000000.0', '50000000.0', '115000000.0',
       '25000000.0', '255000000.0', '16000000.0', '22000000000.0',
       '320000000.0', '125000000.0', '145000000.0', '850000000.0',
       '1800000000.0', '1600000000.0', '420000000.0', '800000000.0',
       '380000000.0', '275000000.0', '520000000.0', '20000000000.0',
       '22000000.0', '950000000.0', '3500000003.0', '590000000.0',
       '1000000000.0', '670000000.0', '490000000.0', '340000000.0',
       '470000000.0', '65000000.0', '2300000000.0', '195000000.0',
       '5200000000.0', '105000000.0', '540000000.0', '2000000000.0',
       '310000000.0', '1250000000.0', '460000000.0', '68000000.0',
       '155000000.0', '930000000.0', '685000000.0', '235000000.0',
       '570000000.0', '4500000000.0', '990000000.0', '3900000000.0',
       '295000000.0', '205000000.0', '6000000000.0', '5495000000.0',
       '9000000000.0', '620000000.0', '138000000.0', '40000000.0',
       '84000000.0', '45000000.0', '5000000.0', '820000000.0',
       '152000000.0', '183000000.0', '153000000.0', '3500000000.0',
       '1550000000.0', '265000000.0', '740000000.0', '780000000.0',
       '7000000000.0', '585000000.0', '1900000000.0', '64000000.0',
       '1541426290.0', '840000000.0', '15000000.0', '2600000000.0',
       '96000000.0', '315000000.0', '365000000.0', '3600000000.0',
       '185000000.0', '1540000000.0', '1850000000.0', '770000000.0',
       '18000000.0', '385000000.0', '2.400000002532e+19', '985000000.0',
       '530000000.0', '1650000000.0', '30000000.0', '8500000000.0',
       '2900000000.0', '29000000000.0', '2200000000.0', '690000000.0',
       '48000000.0', '225000000.0', '425000000.0', '830000000.0',
       '259000000.0', '610000000.0', '7500000000.0', '59000000.0',
       '87000000.0', '30000000000.0', '76000000.0'], dtype=object)

In [275]:
# force conversion to the right data type ("numeric") using the coerce

df['price'] = pd.to_numeric(df['price'], errors='coerce')
df['price']

0      23,936,072,470.00
1         450,000,000.00
2          75,000,000.00
3          75,000,000.00
4         100,000,000.00
              ...
2995    1,700,000,000.00
2996      300,000,000.00
2997      400,000,000.00
2998      500,000,000.00
2999       85,000,000.00
Name: price, Length: 3000, dtype: float64

In [276]:
# Check if any became NaN during force coercion 

nan_prices = df['price'].isnull().sum()
print(f"Prices that failed to convert (NaN): {nan_prices}")

Prices that failed to convert (NaN): 0

In [877]:
# 3. Creating a more readable version in millions from the "price coulumn itself to get another column"

df['price_million_ngn'] = (df['price'] / 1_000_000).round(2)
df['price_million_ngn']

0       7.00
1       3.75
2       3.60
3       7.00
4       6.00
        ...
1355    3.00
1356   80.00
1357    3.00
1358    3.50
1359    2.50
Name: price_million_ngn, Length: 1360, dtype: float64

In [278]:
# creating a column for price in million for better readability on glance

price_loc = df.columns.get_loc('price') + 1
if 'price_million_ngn' in df.columns:
    df.drop(columns=['price_million_ngn'], inplace=True)  
df.insert(price_loc, 'price_million_ngn', (df['price'] / 1_000_000).round(2))

In [279]:
# formatting the price_in_million column for better code undestanding output

def formatted_price(value_millions):
    """
    converts prices from million to either billion or trillion by using 1000 count for billion spotting and 1_000_000 count for trillion
    as 1000 million makes a billion and 1_000_000 million makes a trillion
    after which if it found any output as integer convert it into float for better consistency
    """
    if value_millions >= 1_000_000:           # 1 trillion Naira or more
        trillions = value_millions / 1_000_000
        return f"{trillions:.1f}T" if trillions.is_integer() else f"{trillions:.1f}T"
    elif value_millions >= 1_000:             # 1 billion or more
        billions = value_millions / 1_000
        return f"{billions:.1f}B" if billions.is_integer() else f"{billions:.1f}B"
    else:
        return f"{value_millions:.1f}M" if value_millions.is_integer() else f"{value_millions:.1f}M"

In [280]:
# Apply the formatting

df['price_formatted'] = df['price_million_ngn'].apply(formatted_price)

In [281]:
# Inserting it right after price_in_million for perfect column order

col_order = df.columns.get_loc('price_million_ngn') + 1
df.insert(col_order, 'price_formatted', df.pop('price_formatted'))

In [282]:
df.sample(n=3)

                              property_title          price  price_million_ngn price_formatted                                        description                                           location size_sqm                                        listing_url  bedrooms  bathrooms furnishing_status      agent_name  contact                                        image_links                               property_description property_type listing_date last_updated prize_per_sqm source listing_type
2974  5bdrm Duplex in Lekki Phase 1 for sale 950,000,000.00             950.00          950.0M  For Sale: Massive 5-Bedroom Fully Detached Dup...  PromotedLagos, Lekki, Lekki Phase 1, 2 hours a...      500  https://jiji.ng/lekki-phase/houses-apartments-...         5          5    Semi-Furnished  Promoted Lagos  Unknown  https://pictures-nigeria.jijistatic.net/170906...  For Sale: Massive 5-Bedroom Fully Detached Dup...        Duplex  2 hours ago  2 hours ago     1900000.0   jiji         sale
1684           5bdrm Duplex in Ajah for sale 650,000,000.00             650.00          650.0M  Luxury 5bedroom fully detached duplex for sale...           PromotedLagos, Ajah, 2 hours ago35 views      300  https://jiji.ng/ajah/houses-apartments-for-sal...         5          5    Semi-Furnished      Enterprise  Unknown  https://pictures-nigeria.jijistatic.net/181793...  Subtype Detached Property Address Ajah Propert...        Duplex  2 hours ago  2 hours ago    2166666.67   jiji         sale
674           5bdrm Duplex in Ikota for sale 400,000,000.00             400.00          400.0M  5bedroom fully detached duplex for sale\nameni...     PromotedLagos, Lekki, Ikota, 1 hour ago3 views      280  https://jiji.ng/ikota/houses-apartments-for-sa...         5          5    Semi-Furnished  Promoted Lagos  Unknown  https://pictures-nigeria.jijistatic.net/163194...  Subtype Detached Property Address Ikota Proper...        Duplex   1 hour ago   1 hour ago    1428571.43   jiji         sale

In [283]:
print("\nTOP 5 MOST EXPENSIVE PROPERTIES:")
print("=="*70)
top10 = df[['property_title', 'price_million_ngn', 'price_formatted', 'location']].sort_values('price_million_ngn', ascending=False).head(5)
print(top10.to_string(index=False))

TOP 5 MOST EXPENSIVE PROPERTIES:
============================================================================================================================================
                                         property_title     price_million_ngn price_formatted                                                   location
       Furnished 4bdrm Duplex in Adeniyi Jones for sale 24,000,000,025,320.00     24000000.0T  PromotedLagos, Ikeja, Adeniyi Jones, 3 hours ago107 views
             Furnished 5bdrm Duplex in Chevron for sale  3,589,000,003,370.00      3589000.0T          PromotedLagos, Lekki, Chevron, 2 hours ago5 views
4bdrm Block of Flats in Shericon, Akute Ajuwon for sale             30,000.00           30.0B PromotedLagos, Ikorodu, Akute Ajuwon, 6 hours ago117 views
 20bdrm Block of Flats in Banana Island, Ikoyi for sale             29,000.00           29.0B                  PromotedLagos, Ikoyi, 2 hours ago62 views
      Furnished 7bdrm Mansion in Banana Island for sale             23,936.07           23.9B   PromotedLagos, Ikoyi, Banana Island, 3 hours ago71 views

## SIZE_SQM

In [285]:
data_type = df['size_sqm'].dtype
data_type

dtype('O')

In [286]:
data_outlook = df['size_sqm'].head(10).tolist()
data_outlook

['5000', '350', '648', '200', '300', '500', '3650', '350', '400', '280']

In [287]:
df['size_sqm'].unique()

array(['5000', '350', '648', '200', '300', '500', '3650', '400', '280',
       '1000', '600', '630', '800', '450', '669', '250', '160', '900',
       '380', '540', '1600', '100', '50', '1300', '317', '210', '3800',
       '520', '130', '650', '320', '295', '328', '750', '240', '120',
       '321', '220', '1500', '22', '170', '260', '1200', '80', '420',
       '550', '290', '680', '700', '580', '433', '560', '1100', '620',
       '480', '230', '430', '670', '820', '270', '360', '660', '150',
       'Unknown', '1038', '325', '390', '652', '3600', '330', '720',
       '263', '223', '40', '2000', '640', '1400', '10', '190', '206',
       '1520', '2436', '310', '4556', '453', '850', '1350', '180', '78',
       '45', '237', '218', '289', '535', '340', '870', '1887', '460',
       '370', '510', '1700', '2400', '710', '801', '3000', '435', '90',
       '341', '780', '35', '2380', '1225'], dtype=object)

In [288]:
# Now let's convert from the object(string) value to numeric which is the right value

df['size_sqm'] = pd.to_numeric(df['size_sqm'], errors='coerce')

In [289]:
total_listings = len(df)
missing_size = df['size_sqm'].isnull().sum()
missing_percent = (missing_size / total_listings) * 100
print(missing_size)
print(f"{missing_percent}%")

2
0.06666666666666667%

In [290]:
# I want to fill the missing value with the median since the missing value is less than 5%

    
median_size = df['size_sqm'].median()
print(f"Median size_sqm = {median_size:,.0f} sqm")

df['size_sqm'].fillna(median_size, inplace=True)
df['size_sqm'] = df['size_sqm'].astype('Int64')   # converts output to whole number

Median size_sqm = 350 sqm

In [291]:
df['size_sqm'].isnull().sum()

0

In [292]:
df.head(1)

                                      property_title             price  price_million_ngn price_formatted                                        description                                           location  size_sqm                                        listing_url  bedrooms  bathrooms furnishing_status      agent_name  contact                                        image_links                               property_description property_type listing_date last_updated prize_per_sqm source listing_type
0  Furnished 7bdrm Mansion in Banana Island for sale 23,936,072,470.00          23,936.07           23.9B  * FOR SALE! *\r\nA 7-bedroom stand-alone water...  PromotedLagos, Ikoyi, Banana Island, 3 hours a...      5000  https://jiji.ng/banana-island/houses-apartment...         7          7         Furnished  Promoted Lagos  Unknown  https://pictures-nigeria.jijistatic.net/175289...  * FOR SALE! *\r\nA 7-bedroom stand-alone water...          Land  3 hours ago  3 hours ago    4787214.49   jiji         sale

## PRICE_PER_SQM

In [294]:
df['prize_per_sqm'].isnull().sum()

0

### since we have a new calculated size_sqm, it's best to do away with the old prize_per_sqm and calculate a new one

In [296]:
df.drop(columns=['price_per_sqm', 'prize_per_sqm'], errors='ignore', inplace=True)

In [297]:
df.head(1)

                                      property_title             price  price_million_ngn price_formatted                                        description                                           location  size_sqm                                        listing_url  bedrooms  bathrooms furnishing_status      agent_name  contact                                        image_links                               property_description property_type listing_date last_updated source listing_type
0  Furnished 7bdrm Mansion in Banana Island for sale 23,936,072,470.00          23,936.07           23.9B  * FOR SALE! *\r\nA 7-bedroom stand-alone water...  PromotedLagos, Ikoyi, Banana Island, 3 hours a...      5000  https://jiji.ng/banana-island/houses-apartment...         7          7         Furnished  Promoted Lagos  Unknown  https://pictures-nigeria.jijistatic.net/175289...  * FOR SALE! *\r\nA 7-bedroom stand-alone water...          Land  3 hours ago  3 hours ago   jiji         sale

In [298]:
# creating the new and corrected "price_per_sqm" while converting directly to integer

df['price_per_sqm'] = (df['price'] / df['size_sqm']).round(0).astype('Int64')

In [299]:
# now let's insert the new price_per_sqm after size_sqm to follow the order

size_pos = df.columns.get_loc('size_sqm')
df.insert(size_pos + 1, 'price_per_sqm', df.pop('price_per_sqm'))

In [300]:
df.head(1)

                                      property_title             price  price_million_ngn price_formatted                                        description                                           location  size_sqm  price_per_sqm                                        listing_url  bedrooms  bathrooms furnishing_status      agent_name  contact                                        image_links                               property_description property_type listing_date last_updated source listing_type
0  Furnished 7bdrm Mansion in Banana Island for sale 23,936,072,470.00          23,936.07           23.9B  * FOR SALE! *\r\nA 7-bedroom stand-alone water...  PromotedLagos, Ikoyi, Banana Island, 3 hours a...      5000        4787214  https://jiji.ng/banana-island/houses-apartment...         7          7         Furnished  Promoted Lagos  Unknown  https://pictures-nigeria.jijistatic.net/175289...  * FOR SALE! *\r\nA 7-bedroom stand-alone water...          Land  3 hours ago  3 hours ago   jiji         sale

## BEDROOM AND BATHROOM

In [302]:
columns = ['bedrooms', 'bathrooms']

for col in columns:
    if col not in df.columns:
        print(f"{col} missing")
        df[col] = pd.to_numeric(df[col], errors='coerce')  # converts the column to numeric
    
    # calculates missing percent
    missing = df[col].isnull().sum()
    missing_pct = (missing / len(df)) * 100

    # if missing % is less than the recommended 5%, we fill with median else we live it as it is
    if missing_pct <= 5.0:
        median_val = df[col].median()
        df[col].fillna(median_val, inplace=True)
        df[col] = df[col].astype('Int64')          # converts the now numeric value to integer
        print(f"{col} → imputed with median {median_val}")
    else:
        df[col] = df[col].astype('Int64')
        print(f"{col} → no imputation")

print(df[['property_title', 'size_sqm', 'price_per_sqm', 'bedrooms', 'bathrooms', 'price_formatted']].head(3))

bedrooms → imputed with median 4.0
bathrooms → imputed with median 5.0
                                      property_title  size_sqm  price_per_sqm  bedrooms  bathrooms price_formatted
0  Furnished 7bdrm Mansion in Banana Island for sale      5000        4787214         7          7           23.9B
1           4bdrm Duplex in An Estate Ikeja for sale       350        1285714         4          5          450.0M
2  Furnished 5bdrm Duplex in Shalom Park Estate, ...       648         115741         5          5           75.0M

In [631]:
df.head(1)

                  property_title    price  price_million_ngn price_readable                                        description                                  location  size_sqm  price_per_sqm                                        listing_url  bedrooms  bathrooms furnishing_status  agent_name  contact                                        image_links                               property_description property_type listing_date last_updated source listing_type
0  4bdrm Duplex in Ajah for rent  7000000               7.00         ₦7.00M  FOR RENT 4Bedroom semi detached duplex 7Millio...  PromotedLagos, Ajah, 1 hour ago267 views       240          29167  https://jiji.ng/ajah/houses-apartments-for-ren...         4          4       Unfurnished  Enterprise  Unknown  https://pictures-nigeria.jijistatic.net/183052...  Property Address Ajah,Lekki Lagos. Property Si...        Duplex   1 hour ago   1 hour ago   jiji         rent

In [305]:
pd.set_option('display.max_columns', None)      # show all columns
pd.set_option('display.width', 1000)            # wider output

In [306]:
df.head(1)

                                      property_title             price  price_million_ngn price_formatted                                        description                                           location  size_sqm  price_per_sqm                                        listing_url  bedrooms  bathrooms furnishing_status      agent_name  contact                                        image_links                               property_description property_type listing_date last_updated source listing_type
0  Furnished 7bdrm Mansion in Banana Island for sale 23,936,072,470.00          23,936.07           23.9B  * FOR SALE! *\r\nA 7-bedroom stand-alone water...  PromotedLagos, Ikoyi, Banana Island, 3 hours a...      5000        4787214  https://jiji.ng/banana-island/houses-apartment...         7          7         Furnished  Promoted Lagos  Unknown  https://pictures-nigeria.jijistatic.net/175289...  * FOR SALE! *\r\nA 7-bedroom stand-alone water...          Land  3 hours ago  3 hours ago   jiji         sale

### Now that all important properties has been cleaned, it's time to start handling the others

## PROPERTY TITLE

In [309]:
# check for missing values

missing_porperty_title = df["property_title"].isnull().sum()
missing_porperty_title

0

In [310]:
# Removes white spaces and makes the write up consistent by chnaging the beginning of each word to cap while keeping abbreviation correctly

df['property_title'] = df['property_title'].str.strip().str.title()

In [311]:
df['property_title']

0       Furnished 7Bdrm Mansion In Banana Island For Sale
1                4Bdrm Duplex In An Estate Ikeja For Sale
2       Furnished 5Bdrm Duplex In Shalom Park Estate, ...
3                3Bdrm Block Of Flats In Chevron For Sale
4            3Bdrm Duplex In Golden Haven, Ibeju For Sale
                              ...
2995             5Bdrm Duplex In Ligali Ayorinde For Sale
2996    Furnished 5Bdrm Duplex In Adeniyi Jones Ikeja ...
2997    3Bdrm Apartment In Shonibare Estate, Maryland ...
2998           4Bdrm Duplex In Freedom Way Lekki For Sale
2999       2Bdrm Block Of Flats In Canaan Estate For Sale
Name: property_title, Length: 3000, dtype: object

In [312]:
# 2. Replace abbreviations with full words using regular expressions

replacements = {
    r'\b(\d+)\s*Bdr?m?\b': r'\1 Bedroom',           # 4bdrm, 5bd, 3BDR → 4 Bedroom
    r'\b(\d+)\s*Bd?\b':   r'\1 Bedroom',           # 4bd, 5B → 4 Bedroom
    r'\b(\d+)\s*Bedroom?s?\b': r'\1 Bedroom',      # normalise plural
    r'\bSqm\b': 'sqm',                             # Sqm → sqm
    r'\bSq\.M\b': 'sqm',                           # Sq.M → sqm
    r'\bBq\b': 'BQ',                               # Boy's Quarter
    r'\bW\/C\b': 'WC',                             # Water Closet
    r'\bA\/C\b': 'A/C',                            # Air Conditioning
    r'&': 'and',                                   # & → and
}

# using loop to run and replace all places where abbreviations is found
for pattern, repl in replacements.items():
    df['property_title'] = df['property_title'].str.replace(pattern, repl, regex=True, case=False)

# removing any extra spaces my regular expresion (re) might introduce
df['property_title'] = df['property_title'].str.replace(r'\s+', ' ', regex=True).str.strip()
df['property_title']

0       Furnished 7 Bedroom Mansion In Banana Island F...
1            4 Bedroom Duplex In An Estate Ikeja For Sale
2       Furnished 5 Bedroom Duplex In Shalom Park Esta...
3            3 Bedroom Block Of Flats In Chevron For Sale
4        3 Bedroom Duplex In Golden Haven, Ibeju For Sale
                              ...
2995         5 Bedroom Duplex In Ligali Ayorinde For Sale
2996    Furnished 5 Bedroom Duplex In Adeniyi Jones Ik...
2997    3 Bedroom Apartment In Shonibare Estate, Maryl...
2998       4 Bedroom Duplex In Freedom Way Lekki For Sale
2999    2 Bedroom Block Of Flats In Canaan Estate For ...
Name: property_title, Length: 3000, dtype: object

## DESCRIPTION

#### Since we already have **property_description** which is more detailed, it's best to remove **description** to avoid redundancy

In [315]:
df.drop(columns=['description'], inplace=True)

print("\n'description' column successfully dropped")

'description' column successfully dropped

In [316]:
df.head(1)

                                      property_title             price  price_million_ngn price_formatted                                           location  size_sqm  price_per_sqm                                        listing_url  bedrooms  bathrooms furnishing_status      agent_name  contact                                        image_links                               property_description property_type listing_date last_updated source listing_type
0  Furnished 7 Bedroom Mansion In Banana Island F... 23,936,072,470.00          23,936.07           23.9B  PromotedLagos, Ikoyi, Banana Island, 3 hours a...      5000        4787214  https://jiji.ng/banana-island/houses-apartment...         7          7         Furnished  Promoted Lagos  Unknown  https://pictures-nigeria.jijistatic.net/175289...  * FOR SALE! *\r\nA 7-bedroom stand-alone water...          Land  3 hours ago  3 hours ago   jiji         sale

## FURNISHING STATUS

In [318]:
df['furnishing_status'].isnull().sum()

0

In [319]:
df['furnishing_status'].unique()

array(['Furnished', 'Semi-Furnished', 'Unfurnished'], dtype=object)

In [320]:
value_counts = df['furnishing_status'].value_counts(dropna=False)   #  dropna=False   helps check to also see and include NaN count
value_counts

furnishing_status
Semi-Furnished    1381
Unfurnished       1059
Furnished          560
Name: count, dtype: int64

## AGENT NAME

In [322]:
df["agent_name"].isnull().any()

False

In [323]:
df["agent_name"].unique()

array(['Promoted Lagos', 'Enterprise', 'Diamond', 'Lagos'], dtype=object)

## CONTACT

In [325]:
df["contact"].isnull().sum()

0

In [326]:
df["contact"].unique()

array(['Unknown'], dtype=object)

## IMAGE LINKS

In [328]:
df['image_links'].isnull().sum()

0

In [329]:
df['image_links'].value_counts(dropna=False)

image_links
https://pictures-nigeria.jijistatic.net/182318258_MzAwLTQwMC0xZTk3ZGRhOGQ1.jpg    6
https://pictures-nigeria.jijistatic.net/182939179_MzAwLTQwMC0yYjYyOTMzMTNj.jpg    5
https://pictures-nigeria.jijistatic.net/186534546_MzAwLTM0MC01NWQ5ZDcwYTE4.jpg    5
https://pictures-nigeria.jijistatic.net/183124564_MzAwLTc2OS0xY2IwNmM5YTZl.jpg    5
https://pictures-nigeria.jijistatic.net/178280897_MzAwLTQwMC03M2Q0NDUwZDUx.jpg    5
                                                                                 ..
https://pictures-nigeria.jijistatic.net/184724321_MzAwLTQwMC1jYWRjM2VkZTYy.jpg    1
https://pictures-nigeria.jijistatic.net/174234136_MzAwLTQwMC1mZTg1NDdlYzYw.jpg    1
https://pictures-nigeria.jijistatic.net/184939376_MzAwLTM0Ni1iNGYzMDE0MGM3.jpg    1
https://pictures-nigeria.jijistatic.net/186646025_MzAwLTQwMC01ZjUyMDZhNjhh.jpg    1
https://pictures-nigeria.jijistatic.net/176980586_MzAwLTIyNS1mZjM2YzBiNmFi.jpg    1
Name: count, Length: 1988, dtype: int64

In [330]:
df['image_links'].unique()

array(['https://pictures-nigeria.jijistatic.net/175289597_MzAwLTIwMi1mYWYxZGEwMDg1.jpg',
       'https://pictures-nigeria.jijistatic.net/183589524_MzAwLTQwMC1mNzExZDA0MjMz.jpg',
       'https://pictures-nigeria.jijistatic.net/182283198_MzAwLTQwMC0yYzg4ZTdlZTIx.jpg',
       ...,
       'https://pictures-nigeria.jijistatic.net/171338436_MzAwLTIyNS01NDIwNzJiYjIy.jpg',
       'https://pictures-nigeria.jijistatic.net/80776833_MzAwLTQwMC04ZTJjMGVmOTg4.jpg',
       'https://pictures-nigeria.jijistatic.net/176980586_MzAwLTIyNS1mZjM2YzBiNmFi.jpg'],
      dtype=object)

## PROPERTY DESCRIPTION

In [332]:
df['property_description'].isnull().sum()

0

In [333]:
#  Stripping out leading/trailing whitespace and also removing multiple spaces/newlines
df['property_description'] = (
    df['property_description']
    .astype(str)                                   
    .str.strip()                                   # remove leading/trailing spaces & \n
    .str.replace(r'\s+', ' ', regex=True)          # collapse any whitespace (spaces, \n, \t) into single space
    .replace('nan', '')                            # if any NaN became string "nan" as a result of the regular expression
    .str.strip()                                   # final strip to check and remove any white space again
    .str.lower()                                   # coverting all text to lower
)

In [334]:
df['property_description']

0       * for sale! * a 7-bedroom stand-alone waterfro...
1       subtype detached property address an estate ik...
2       subtype detached property address shalom park ...
3       3bedroom serviced apartment available for sale...
4       subtype semi-detached property address eko ake...
                              ...
2995    2 units of fully detached duplexes in victoria...
2996    7 units 5 bedroom service and fully furnished ...
2997    property address maryland estate name shonibar...
2998    subtype detached property address freedom way ...
2999    property address canaan estate located at abra...
Name: property_description, Length: 3000, dtype: object

## PROPERTY TYPE

In [336]:
df['property_type'].isnull().sum()

0

In [337]:
df['property_type'].astype(str).unique()

array(['Land', 'Duplex', 'Flat', 'Mansion', 'Bungalow', 'Apartment',
       'Self Contain', 'Unknown', 'Terrace'], dtype=object)

In [338]:
df['property_type'].value_counts(dropna=False)

property_type
Duplex          2319
Apartment        308
Flat             165
Unknown           91
Bungalow          50
Mansion           24
Land              20
Self Contain      18
Terrace            5
Name: count, dtype: int64

In [339]:
unknown_count = (df['property_type'] == 'Unknown').sum()
unknown_percent  = unknown_count / len(df) * 100

print(unknown_percent)

3.033333333333333

In [340]:
#  filling out unknown with something more formal

# df['property_type'] = df['property_type'].replace('Unknown', 'Commercial / Other')

## DATES
 - #### I will be using my scraped real date **(2025-11-17 at 17:44 UTC)** as a reference to calculating and converting my dates column

In [342]:
from datetime import datetime, timedelta
import re

SCRAPE_DATE = datetime(2025, 11, 17, 17, 44, 0)

## LISTING DATE

In [344]:
df['listing_date'].isnull().sum()

0

In [345]:
df['listing_date'].unique().tolist()

['3 hours ago',
 '1 hour ago',
 '2 hours ago',
 '5 hours ago',
 '9 hours ago',
 '6 days ago',
 '8 hours ago',
 '6 hours ago',
 '1 day ago',
 'Unknown',
 '3 days ago',
 '2 days ago',
 '10 hours ago',
 '20 hours ago',
 '11 hours ago',
 '7 hours ago',
 '2 weeks ago',
 '5 days ago']

In [346]:
df['listing_date'].value_counts()

listing_date
2 hours ago     1066
1 hour ago       999
3 hours ago      484
6 hours ago      239
5 hours ago      106
9 hours ago       41
8 hours ago       17
2 days ago        12
1 day ago         12
7 hours ago        6
Unknown            4
3 days ago         4
6 days ago         4
10 hours ago       2
20 hours ago       1
11 hours ago       1
2 weeks ago        1
5 days ago         1
Name: count, dtype: int64

In [347]:
mode_value = df['listing_date'].mode()[0]
mode_value

'2 hours ago'

In [348]:
# Count "Unknown"

unknown_count = (df['listing_date'] == 'Unknown').sum()
unknown_percent = unknown_count / len(df) * 100

print(f"{unknown_percent}%")

0.13333333333333333%

In [349]:
# since the missing/unknown for the listing_date is significantly small, i can then replace with the mode since it's not logical to calculate the median

print(f"Replacing the unknown values with the mode which is: {mode_value}\n")
df['listing_date'] = df['listing_date'].replace('Unknown', mode_value)
print("Successfully replaced the unknown with the mode")

Replacing the unknown values with the mode which is: 2 hours ago

Successfully replaced the unknown with the mode

In [350]:
# Now time to convert to real datetime

def date_conversion_parser(text):
    if pd.isna(text):
        return pd.NaT                         # not a time
    text = str(text).lower()
    num = int(re.search(r'(\d+)', text).group(1)) if re.search(r'\d+', text) else 0
    
    if 'minute' in text or 'now' in text:  return SCRAPE_DATE
    if 'hour'   in text:  return SCRAPE_DATE - timedelta(hours=num)
    if 'day'    in text:  return SCRAPE_DATE - timedelta(days=num)
    if 'week'   in text:  return SCRAPE_DATE - timedelta(weeks=num)
    if 'month'  in text:  return SCRAPE_DATE - timedelta(days=num*30)
    if 'year'   in text:  return SCRAPE_DATE - timedelta(days=num*365)
    return SCRAPE_DATE

In [351]:
df['listing_date'] = df['listing_date'].apply(date_conversion_parser)

In [352]:
df['listing_date']

0      2025-11-17 14:44:00
1      2025-11-17 16:44:00
2      2025-11-17 15:44:00
3      2025-11-17 15:44:00
4      2025-11-17 15:44:00
               ...
2995   2025-11-17 15:44:00
2996   2025-11-17 14:44:00
2997   2025-11-17 15:44:00
2998   2025-11-17 15:44:00
2999   2025-11-17 08:44:00
Name: listing_date, Length: 3000, dtype: datetime64[ns]

In [353]:
df.head(1)

                                      property_title             price  price_million_ngn price_formatted                                           location  size_sqm  price_per_sqm                                        listing_url  bedrooms  bathrooms furnishing_status      agent_name  contact                                        image_links                               property_description property_type        listing_date last_updated source listing_type
0  Furnished 7 Bedroom Mansion In Banana Island F... 23,936,072,470.00          23,936.07           23.9B  PromotedLagos, Ikoyi, Banana Island, 3 hours a...      5000        4787214  https://jiji.ng/banana-island/houses-apartment...         7          7         Furnished  Promoted Lagos  Unknown  https://pictures-nigeria.jijistatic.net/175289...  * for sale! * a 7-bedroom stand-alone waterfro...          Land 2025-11-17 14:44:00  3 hours ago   jiji         sale

## LAST UPDATED

In [355]:
df['last_updated'].isnull().sum()

0

In [356]:
df['last_updated'].unique().tolist()

['3 hours ago',
 '1 hour ago',
 '2 hours ago',
 '5 hours ago',
 '9 hours ago',
 '6 days ago',
 '8 hours ago',
 '6 hours ago',
 '1 day ago',
 'Unknown',
 '3 days ago',
 '2 days ago',
 '10 hours ago',
 '20 hours ago',
 '11 hours ago',
 '7 hours ago',
 '2 weeks ago',
 '5 days ago']

In [357]:
df['last_updated'].value_counts()

last_updated
2 hours ago     1066
1 hour ago       999
3 hours ago      484
6 hours ago      239
5 hours ago      106
9 hours ago       41
8 hours ago       17
2 days ago        12
1 day ago         12
7 hours ago        6
Unknown            4
3 days ago         4
6 days ago         4
10 hours ago       2
20 hours ago       1
11 hours ago       1
2 weeks ago        1
5 days ago         1
Name: count, dtype: int64

In [358]:
mode_value = df['last_updated'].mode()[0]
mode_value

'2 hours ago'

In [359]:
# Count "Unknown"

unknown_count = (df['last_updated'] == 'Unknown').sum()
unknown_percent = unknown_count / len(df) * 100

print(f"{unknown_percent}%")

0.13333333333333333%

In [360]:
# since the missing/unknown for the last_updated is significantly small, i can then replace with the mode since it's not logical to calculate the median

print(f"Replacing the unknown values with the mode which is: {mode_value}\n")
df['last_updated'] = df['last_updated'].replace('Unknown', mode_value)
print("Successfully replaced the unknown with the mode")

Replacing the unknown values with the mode which is: 2 hours ago

Successfully replaced the unknown with the mode

In [361]:
df['last_updated'] = df['last_updated'].apply(date_conversion_parser)

In [362]:
df['last_updated']

0      2025-11-17 14:44:00
1      2025-11-17 16:44:00
2      2025-11-17 15:44:00
3      2025-11-17 15:44:00
4      2025-11-17 15:44:00
               ...
2995   2025-11-17 15:44:00
2996   2025-11-17 14:44:00
2997   2025-11-17 15:44:00
2998   2025-11-17 15:44:00
2999   2025-11-17 08:44:00
Name: last_updated, Length: 3000, dtype: datetime64[ns]

In [363]:
df.sample(n = 1)

                                     property_title          price  price_million_ngn price_formatted                                          location  size_sqm  price_per_sqm                                        listing_url  bedrooms  bathrooms furnishing_status      agent_name  contact                                        image_links                               property_description property_type        listing_date        last_updated source listing_type
896  4 Bedroom Duplex In Chevron Toll Gate For Sale 125,000,000.00             125.00          125.0M  PromotedLagos, Lekki, Chevron, 1 hour ago5 views       450         277778  https://jiji.ng/chevron/houses-apartments-for-...         4          4       Unfurnished  Promoted Lagos  Unknown  https://pictures-nigeria.jijistatic.net/143825...  property address 4bedroom semi detached duplex...        Duplex 2025-11-17 16:44:00 2025-11-17 16:44:00   jiji         sale

## NOW TIME TO SAVE MY CLEANED DATA IN JSON FORMAT AS WELL

In [365]:
# Saving The Now Cleaned File as JSON Format

import os

# Path to my cleaned folder
cleaned_folder = r"Data Science Program\KWE4 STUDIO\LagosPropIQ\data\cleaned"
os.makedirs(cleaned_folder, exist_ok=True)

# Final JSON path
final_json_path = os.path.join(cleaned_folder, "sales_cleaned.json")

# Save as JSON — preserves ALL data types perfectly (Int64, datetime, etc.)
df.to_json(final_json_path, orient='records', date_format='iso', force_ascii=False, indent=2)

print("="*80)
print("SALES DATA SUCCESSFULLY SAVED AS JSON!")
print("="*80)
print(f"Location : {final_json_path}")
print(f"Rows     : {len(df):,} listings")
print(f"File size: ~{os.path.getsize(final_json_path)/1024/1024:.1f} MB")

================================================================================
SALES DATA SUCCESSFULLY SAVED AS JSON!
================================================================================
Location : Data Science Program\KWE4 STUDIO\LagosPropIQ\data\cleaned\sales_cleaned.json
Rows     : 3,000 listings
File size: ~3.6 MB

# ALL DONE FOR SALES JIJI WEB SCRAPER

# BEGINNING OF RENT JIJI WE SCRAPER CLEANING

In [997]:
# Loading the dataset

df_rent = pd.read_json("lagos_rent_raw_20251117_174452.json")
df_rent.sample(n=2, random_state=42)

                                         property_title     price                                        description                                           location size_sqm                                        listing_url  bedrooms  bathrooms furnishing_status agent_name  contact                                        image_links                               property_description property_type listing_date last_updated prize_per_sqm source listing_type
51    Furnished 4bdrm Townhouse / Terrace in Park Vi...  30000000  To Let\nParkview Estate IKOYI\nFULLY FURNISHED...  PromotedLagos, Ikoyi, Parkview Estate, 2 hours...      500  https://jiji.ng/parkview-estate/houses-apartme...         4          4         Furnished    Diamond  Unknown  https://pictures-nigeria.jijistatic.net/185258...  Property Address Ajayi Bembe str Estate Name P...       Terrace  2 hours ago  2 hours ago       60000.0   jiji         rent
1101                  4bdrm Apartment in Ikota for rent   8000000  TO LET \nLuxury semi detached 4 bedroom Apartm...   PromotedLagos, Lekki, Ikota, 2 hours ago36 views      500  https://jiji.ng/ikota/houses-apartments-for-re...         4          4       Unfurnished    Diamond  Unknown  https://pictures-nigeria.jijistatic.net/182957...  Property Address Ikota Property Size 500 sqm S...     Apartment  2 hours ago  2 hours ago       16000.0   jiji         rent

## GENERAL CHECK

In [635]:
# checking for duplicates

df_rent.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1355    False
1356    False
1357    False
1358    False
1359    False
Length: 1360, dtype: bool

In [637]:
# checking for missing numbers

df_rent.isnull().sum()

property_title          0
price                   0
description             0
location                0
size_sqm                0
listing_url             0
bedrooms                0
bathrooms               0
furnishing_status       0
agent_name              0
contact                 0
image_links             0
property_description    0
property_type           0
listing_date            0
last_updated            0
prize_per_sqm           0
source                  0
listing_type            0
dtype: int64

In [639]:
# Checking columns and their data types

df_rent.dtypes

property_title          object
price                    int64
description             object
location                object
size_sqm                object
listing_url             object
bedrooms                 int64
bathrooms                int64
furnishing_status       object
agent_name              object
contact                 object
image_links             object
property_description    object
property_type           object
listing_date            object
last_updated            object
prize_per_sqm           object
source                  object
listing_type            object
dtype: object

In [641]:
# Identifying the shape of the data

shape = df_rent.shape
print(f"rent jiji property has column: {shape[1]} and row: {shape[0]:,}")

rent jiji property has column: 19 and row: 1,360

# COLUMN CHECKS, CLEANING, CONVERSION TO RIGHT DATA TYPE E.T.C

In [643]:
# adding commas to my displays for better readability as well

pd.options.display.float_format = '{:,.2f}'.format

## LISTING URL

In [645]:
# checking for missing values using the unique identifier (listing url)

missing_listing_url = df_rent['listing_url'].isnull().sum()
missing_listing_url

0

In [647]:
# checking for duplicates

print("\n" + "="*60)
print("Checking duplicates by listing_url")
print("="*60)

before = len(df_rent)
print(f"Listings before deduplication: {before:,}")

# Count how many exact duplicate URLs exist
dup_urls = df_rent['listing_url'].duplicated().sum()
print(f"Exact duplicate URLs found: {dup_urls}")

============================================================
Checking duplicates by listing_url
============================================================
Listings before deduplication: 1,360
Exact duplicate URLs found: 0

In [649]:
# final detailed checking for duplicates

if df_rent['listing_url'].duplicated().any():
    print("Warning: Still have duplicates!")
else:
    print("Perfect – All listing_url are now unique")

Perfect – All listing_url are now unique

## PRICE

In [929]:
# adding commas to my displays for better readability as well

pd.options.display.float_format = '{:,.2f}'.format

In [931]:
# checking for missing values

missing_price = df_rent['price'].isnull().sum()
missing_price

0

In [1047]:
# checking to see the unique values

df_rent['price'].unique()

array([         7000000,          3750000,          3600000,
                6000000,         80000000,         70000000,
               12000000,           800000,          3000000,
               25000000,          8500000,         35000000,
                2500000,           200000,          6500000,
               13000000,          2000000,           450000,
                1800000,         10000000,          4000000,
               17000000,           600000,          5000000,
                7500000,         16000000,         50000000,
               11000000,         18000000,          3500000,
               30000000,         31500000, 1800000102000000,
               40000000,         15000000,          2300000,
              120000000,          8000000,           650000,
               14000000,          9000000,          1600000,
               20000000,          4500000,           300000,
                1700000,           500000,           750000,
                5200000,         13500000,          1300000,
                1500000,           100000,          1200000,
                2700000,           360000,        250000000,
               24000000,          5500000,          3700000,
                4200000,         45000000,         60000000,
                1100000,         21000000,          1900000,
              260000000,        600000000,          2800000,
              100000000,        130000000,       5000000000,
              400000000,         13400000,          2400000,
                 550000,         22000000,           350000,
                4700000,          1000000,         10500000,
                 900000,          1400000,         11500000,
                 700000,            32000,        150000000,
                9500000,         27000000,         12500000,
              160000000,        700000000,         36000000,
               26000000,         23000000,        370000000,
                 250000,         17500000,           230000,
               90267650,        240000000,           120000,
                9100000,          2600000,        230000000,
                2200000,        390000000,          3800000,
               55000000,         75000000], dtype=int64)

In [1049]:
# removing white spaces

df_rent['price'] = df_rent['price'].astype(str).str.strip()
df_rent['price']

0        7000000
1        3750000
2        3600000
3        7000000
4        6000000
          ...
1355     3000000
1356    80000000
1357     3000000
1358     3500000
1359     2500000
Name: price, Length: 1360, dtype: object

In [1051]:
# force conversion to the right data type ("numeric") using the coerce

df_rent['price'] = pd.to_numeric(df_rent['price'], errors='coerce')
df_rent['price']

0        7000000
1        3750000
2        3600000
3        7000000
4        6000000
          ...
1355     3000000
1356    80000000
1357     3000000
1358     3500000
1359     2500000
Name: price, Length: 1360, dtype: int64

In [1053]:
# Check if any became NaN during force coercion 

nan_prices = df_rent['price'].isnull().sum()
print(f"Prices that failed to convert (NaN): {nan_prices}")

Prices that failed to convert (NaN): 0

In [1055]:
# creating million column 

df_rent['price_million_ngn'] = (df_rent['price'] / 1_000_000).round(3)
df_rent['price_million_ngn']

0       7.00
1       3.75
2       3.60
3       7.00
4       6.00
        ...
1355    3.00
1356   80.00
1357    3.00
1358    3.50
1359    2.50
Name: price_million_ngn, Length: 1360, dtype: float64

In [1057]:
def price_format(price_ngn):
    if pd.isna(price_ngn):
        return ""
    
    price_ngn = float(price_ngn)
    
    if price_ngn >= 1_000_000:
        value = price_ngn / 1_000_000
        if value >= 10:
            return f"₦{value:.1f}M".replace('.0M', 'M')
        else:
            formatted = f"₦{value:.2f}M"
            return formatted.rstrip('0').rstrip('.') if '.' in formatted else formatted
    
    elif price_ngn >= 100_000:
        value = price_ngn / 1_000
        return f"₦{value:.0f}K"
    
    else:  
        return f"₦{price_ngn:,.0f}"

In [1059]:
# applying the readable format price

df_rent['price_readable'] = df_rent['price'].apply(price_format)
df_rent['price_readable']

0       ₦7.00M
1       ₦3.75M
2       ₦3.60M
3       ₦7.00M
4       ₦6.00M
         ...
1355    ₦3.00M
1356      ₦80M
1357    ₦3.00M
1358    ₦3.50M
1359    ₦2.50M
Name: price_readable, Length: 1360, dtype: object

In [1061]:
# inserting in the right order right after 'price'

price_loc = df.columns.get_loc('price') + 1
price_loc

2

In [1063]:
# Insert price_million_ngn first

df_rent.insert(price_loc, 'price_million_ngn', df_rent.pop('price_million_ngn'))

In [1065]:
# Now inserting price_readable right after it

df_rent.insert(price_loc + 1, 'price_readable', df_rent.pop('price_readable'))

In [1067]:
df_rent.tail(2)

                                        property_title    price  price_million_ngn price_readable                                        description                                           location  size_sqm  price_per_sqm                                        listing_url  bedrooms  bathrooms furnishing_status      agent_name  contact                                        image_links                               property_description property_type listing_date last_updated source listing_type
1358  2bdrm Townhouse / Terrace in Ago Palace for rent  3500000               3.50         ₦3.50M  Standard sharp newly two bedroom terrace duple...  PromotedLagos, Isolo, Ago Palace, 2 hours ago5...    600.00           5833  https://jiji.ng/ago-palace/houses-apartments-f...         2          2       Unfurnished  Promoted Lagos  Unknown  https://pictures-nigeria.jijistatic.net/157666...  Standard sharp newly two bedroom terrace duple...        Duplex  2 hours ago  2 hours ago   jiji         rent
1359                  Mini Flat in Ago Palace for rent  2500000               2.50         ₦2.50M  To let standard luxury newly built MINIFLAT up...  PromotedLagos, Isolo, Ago Palace, 2 hours ago3...    600.00           4167  https://jiji.ng/ago-palace/houses-apartments-f...         1          1       Unfurnished         Diamond  Unknown  https://pictures-nigeria.jijistatic.net/186306...  To let standard luxury newly built MINIFLAT up...          Flat  2 hours ago  2 hours ago   jiji         rent

## SIZE IN SQM

In [963]:
data_type = df_rent['size_sqm'].dtype
data_type

dtype('O')

In [965]:
data_outlook = df_rent['size_sqm'].head(10).tolist()
data_outlook

['240', '340', '1000', '280', '300', '700', '500', '560', '1200', '200']

In [967]:
df_rent['size_sqm'].unique()

array(['240', '340', '1000', '280', '300', '700', '500', '560', '1200',
       '200', '800', '5000', '350', '100', '400', '1010', '30', '150',
       '250', '600', '2000', '185', '450', '35', '120', '1580', '908',
       '1600', '1500', '890', 'Unknown', '180', '550', '10', '229', '45',
       '900', '60', '3000', '110', '50', '20', '25', '85', '260', '245',
       '725', '650', '680', '315', '11', '158', '520', '75', '90', '270',
       '268', '750', '551', '325', '455', '902', '80', '68', '140', '230',
       '285', '210', '290', '545', '2400', '547', '625', '555', '620',
       '130', '648', '65', '235', '353', '1300', '70', '12', '33', '126',
       '66', '233', '23'], dtype=object)

In [1027]:
# Now let's convert from the object(string) value to numeric which is the right value

df_rent['size_sqm'] = pd.to_numeric(df_rent['size_sqm'], errors='coerce')

In [1029]:
total_listings = len(df_rent)
missing_size = df_rent['size_sqm'].isnull().sum()
missing_percent = (missing_size / total_listings) * 100
print(missing_size)
print(f"{missing_percent}%")

6
0.4411764705882353%

In [973]:
# I want to fill the missing value with the median since the missing value is less than 5%

    
median_size = df_rent['size_sqm'].median()
print(f"Median size_sqm = {median_size:,.0f} sqm")

df_rent['size_sqm'].fillna(median_size, inplace=True)
df_rent['size_sqm'] = df_rent['size_sqm'].astype('Int64')   # converts output to whole number(integer)

Median size_sqm = 450 sqm

In [589]:
df_rent
['size_sqm'].isnull().sum()

0

In [977]:
df_rent['size_sqm'].unique()

<IntegerArray>
[240, 340, 1000, 280, 300, 700, 500, 560, 1200, 200, 800, 5000, 350, 100, 400, 1010, 30, 150, 250, 600, 2000, 185, 450, 35, 120, 1580, 908, 1600, 1500, 890, 180, 550, 10, 229, 45, 900, 60, 3000, 110, 50, 20, 25, 85, 260, 245, 725, 650, 680, 315, 11, 158, 520, 75, 90, 270, 268, 750, 551, 325, 455, 902, 80, 68, 140, 230, 285, 210, 290, 545, 2400, 547, 625, 555, 620, 130, 648, 65, 235, 353, 1300, 70, 12, 33, 126, 66, 233, 23]
Length: 87, dtype: Int64

In [995]:
df_rent.head(1)

                  property_title    price  price_million_ngn price_readable                                        description                                  location  size_sqm  price_per_sqm                                        listing_url  bedrooms  bathrooms furnishing_status  agent_name  contact                                        image_links                               property_description property_type listing_date last_updated source listing_type
0  4bdrm Duplex in Ajah for rent  7000000               7.00         ₦7.00M  FOR RENT 4Bedroom semi detached duplex 7Millio...  PromotedLagos, Ajah, 1 hour ago267 views       240          29167  https://jiji.ng/ajah/houses-apartments-for-ren...         4          4       Unfurnished  Enterprise  Unknown  https://pictures-nigeria.jijistatic.net/183052...  Property Address Ajah,Lekki Lagos. Property Si...        Duplex   1 hour ago   1 hour ago   jiji         rent

## PRICE PER SQM -->  DERIVED COLUMN

In [1081]:
df_rent['price_per_sqm'].isnull().sum()

6

In [1069]:
df_rent.head(1)

                  property_title    price  price_million_ngn price_readable                                        description                                  location  size_sqm  price_per_sqm                                        listing_url  bedrooms  bathrooms furnishing_status  agent_name  contact                                        image_links                               property_description property_type listing_date last_updated source listing_type
0  4bdrm Duplex in Ajah for rent  7000000               7.00         ₦7.00M  FOR RENT 4Bedroom semi detached duplex 7Millio...  PromotedLagos, Ajah, 1 hour ago267 views    240.00          29167  https://jiji.ng/ajah/houses-apartments-for-ren...         4          4       Unfurnished  Enterprise  Unknown  https://pictures-nigeria.jijistatic.net/183052...  Property Address Ajah,Lekki Lagos. Property Si...        Duplex   1 hour ago   1 hour ago   jiji         rent

### since we have a new calculated size_sqm, it's best to do away with the old prize_per_sqm and calculate a new one

In [1009]:
df_rent.drop(columns=['price_per_sqm', 'prize_per_sqm'], errors='ignore', inplace=True)

In [1073]:
# creating a new column for the new and corrected "price_per_sqm" while converting directly to integer

df_rent['price_per_sqm'] = (df_rent['price'] / df_rent['size_sqm']).round(0).astype('Int64')

In [1085]:
# now let's insert the new price_per_sqm after size_sqm to follow the order

size_pos = df_rent.columns.get_loc('size_sqm')
df_rent.insert(size_pos + 1, 'price_per_sqm', df_rent.pop('price_per_sqm'))

In [1097]:
df_rent['price_per_sqm'].isnull().any()

True

In [1101]:
total_length = len(df_rent['price_per_sqm'])
missing_size = df_rent['price_per_sqm'].isnull().sum()
missing_percent = (missing_size / total_listings) * 100

print(total_length)
print(missing_size)
print(f"{missing_percent}%")

1360
6
0.4411764705882353%

In [1119]:
df_rent['price_per_sqm'].sort_values(ascending=False)

59      6000000340000
1120         15000000
1283         10000000
1290          7800000
1325          5000000
            ...
107              <NA>
108              <NA>
146              <NA>
148              <NA>
266              <NA>
Name: price_per_sqm, Length: 1360, dtype: Int64

In [1125]:
df_rent['price_per_sqm'].unique()

<IntegerArray>
[   29167,    11029,     3600,    25000,    20000,    10000,   160000,   125000,     4000,     3750,
 ...
 10000000,     3667,   900000,  7800000,     1150,     1900,    10625,   687500,   833333,  1600000]
Length: 330, dtype: Int64

####  since the missing size is below the 5%, I can safely fill out with the  mode or median because i observed that the mean is outrageous in size "4431433365.987445"

In [1157]:
# so I will fill out the missing values with the mode which is 60,000

mode_size = df_rent['price_per_sqm'].mode()
print(f"Mode size_sqm = {mode_size} sqm")

df_rent['price_per_sqm'].fillna(mode_size, inplace=True)

Mode size_sqm = 0    60000
Name: price_per_sqm, dtype: Int64 sqm

In [1159]:
df_rent['price_per_sqm'].isnull().sum()

6

## BEDROOM AND BATHROOM

In [1083]:
columns = ['bedrooms', 'bathrooms']

for col in columns:
    if col not in df_rent.columns:
        print(f"{col} missing")
        df_rent[col] = pd.to_numeric(df_rent[col], errors='coerce')  # converts the column to numeric
    
    # calculates missing percent
    missing = df_rent[col].isnull().sum()
    missing_pct = (missing / len(df_rent)) * 100

    # if missing % is less than the recommended 5%, we fill with median else we live it as it is
    if missing_pct <= 5.0:
        median_val = df_rent[col].median()
        df_rent[col].fillna(median_val, inplace=True)
        df_rent[col] = df_rent[col].astype('Int64')          # converts the now numeric value to integer
        print(f"{col} → imputed with median {median_val}")
    else:
        df_rent[col] = df_rent[col].astype('Int64')
        print(f"{col} → no imputation")

print(df_rent[['property_title', 'size_sqm', 'price_per_sqm', 'bedrooms', 'bathrooms', 'price_readable']].head(2))

bedrooms → imputed with median 3.0
bathrooms → imputed with median 3.0
                                      property_title  size_sqm  price_per_sqm  bedrooms  bathrooms price_readable
0                      4bdrm Duplex in Ajah for rent    240.00          29167         4          4         ₦7.00M
1  3bdrm Bungalow in Peak Prime Estate, Sangotedo...    340.00          11029         3          3         ₦3.75M

In [1161]:
df_rent.head(1)

                  property_title    price  price_million_ngn price_readable                                        description                                  location  size_sqm  price_per_sqm                                        listing_url  bedrooms  bathrooms furnishing_status  agent_name  contact                                        image_links                               property_description property_type listing_date last_updated source listing_type
0  4bdrm Duplex in Ajah for rent  7000000               7.00         ₦7.00M  FOR RENT 4Bedroom semi detached duplex 7Millio...  PromotedLagos, Ajah, 1 hour ago267 views    240.00          29167  https://jiji.ng/ajah/houses-apartments-for-ren...         4          4       Unfurnished  Enterprise  Unknown  https://pictures-nigeria.jijistatic.net/183052...  Property Address Ajah,Lekki Lagos. Property Si...        Duplex   1 hour ago   1 hour ago   jiji         rent

## PROPERTY TITLE

In [1164]:
# check for missing values

missing_porperty_title = df_rent["property_title"].isnull().sum()
missing_porperty_title

0

In [1170]:
# Removes white spaces and makes the write up consistent by chnaging the beginning of each word to cap while keeping abbreviation correctly

df_rent['property_title'] = df_rent['property_title'].str.strip().str.title()

In [1178]:
# 2. Replace abbreviations with full words using regular expressions

replacements = {
    r'\b(\d+)\s*Bdr?m?\b': r'\1 Bedroom',           # 4bdrm, 5bd, 3BDR → 4 Bedroom
    r'\b(\d+)\s*Bd?\b':   r'\1 Bedroom',           # 4bd, 5B → 4 Bedroom
    r'\b(\d+)\s*Bedroom?s?\b': r'\1 Bedroom',      # normalise plural
    r'\bSqm\b': 'sqm',                             # Sqm → sqm
    r'\bSq\.M\b': 'sqm',                           # Sq.M → sqm
    r'\bBq\b': 'BQ',                               # Boy's Quarter
    r'\bW\/C\b': 'WC',                             # Water Closet
    r'\bA\/C\b': 'A/C',                            # Air Conditioning
    r'&': 'and',                                   # & → and
}

# using loop to run and replace all places where abbreviations is found
for pattern, repl in replacements.items():
    df_rent['property_title'] = df_rent['property_title'].str.replace(pattern, repl, regex=True, case=False)

# removing any extra spaces my regular expresion (re) might introduce
df_rent['property_title'] = df_rent['property_title'].str.replace(r'\s+', ' ', regex=True).str.strip()
df_rent['property_title']

0                       4 Bedroom Duplex in Ajah for rent
1       3 Bedroom Bungalow in Peak Prime Estate, Sango...
2       3 Bedroom Block of Flats in Addo Road, Ado / A...
3       4 Bedroom Townhouse / Terrace in Chevron for rent
4       Furnished 4 Bedroom Duplex in Isheri North Gra...
                              ...
1355           2 Bedroom Apartment in Ago Palace for rent
1356     Furnished 5 Bedroom Maisonette in Ikoyi for rent
1357           2 Bedroom Apartment in Ago Palace for rent
1358    2 Bedroom Townhouse / Terrace in Ago Palace fo...
1359                     Mini Flat in Ago Palace for rent
Name: property_title, Length: 1360, dtype: object

## DESCRIPTION

#### Since we already have **property_description** which is more detailed, it's best to remove **description** to avoid redundancy

In [1182]:
df_rent.head(1)

                      property_title    price  price_million_ngn price_readable                                        description                                  location  size_sqm  price_per_sqm                                        listing_url  bedrooms  bathrooms furnishing_status  agent_name  contact                                        image_links                               property_description property_type listing_date last_updated source listing_type
0  4 Bedroom Duplex in Ajah for rent  7000000               7.00         ₦7.00M  FOR RENT 4Bedroom semi detached duplex 7Millio...  PromotedLagos, Ajah, 1 hour ago267 views    240.00          29167  https://jiji.ng/ajah/houses-apartments-for-ren...         4          4       Unfurnished  Enterprise  Unknown  https://pictures-nigeria.jijistatic.net/183052...  property address ajah,lekki lagos. property si...        Duplex   1 hour ago   1 hour ago   jiji         rent

In [1184]:
df_rent.drop(columns=['description'], inplace=True)

print("\n'description' column successfully dropped")

'description' column successfully dropped

In [1186]:
df_rent.head(1)

                      property_title    price  price_million_ngn price_readable                                  location  size_sqm  price_per_sqm                                        listing_url  bedrooms  bathrooms furnishing_status  agent_name  contact                                        image_links                               property_description property_type listing_date last_updated source listing_type
0  4 Bedroom Duplex in Ajah for rent  7000000               7.00         ₦7.00M  PromotedLagos, Ajah, 1 hour ago267 views    240.00          29167  https://jiji.ng/ajah/houses-apartments-for-ren...         4          4       Unfurnished  Enterprise  Unknown  https://pictures-nigeria.jijistatic.net/183052...  property address ajah,lekki lagos. property si...        Duplex   1 hour ago   1 hour ago   jiji         rent

## FURNISHING STATUS

In [1189]:
df_rent['furnishing_status'].isnull().sum()

0

In [1191]:
df_rent['furnishing_status'].unique()

array(['Unfurnished', 'Semi-Furnished', 'Furnished'], dtype=object)

In [ ]:
value_counts = df_rent['furnishing_status'].value_counts(dropna=False)   #  dropna=False   helps check to also see and include NaN count
value_counts

## AGENT

In [1196]:
df_rent['agent_name'].isnull().sum()

0

In [1198]:
df_rent['agent_name'].unique()

array(['Enterprise', 'Lagos', 'Diamond', 'Promoted Lagos'], dtype=object)

## CONTACT

In [1201]:
df_rent['contact'].isnull().sum()

0

In [1203]:
df_rent['contact'].unique()

array(['Unknown'], dtype=object)

## IMAGE LINKS

In [1206]:
df_rent['image_links'].isnull().sum()

0

In [1208]:
df_rent['image_links'].value_counts()

image_links
https://pictures-nigeria.jijistatic.net/186190532_MzAwLTQ4OC1mOTVkNGYxMDJi.jpg       4
https://pictures-nigeria.jijistatic.net/182662719_MzAwLTQwMC1iOTc5Y2U5MWYy.jpg       4
https://pictures-nigeria.jijistatic.net/179537873_MzAwLTQwMC05MGE1OTZjYTBi.jpg       4
https://pictures-nigeria.jijistatic.net/179318727_MzAwLTQwMC00ZDZkNzJhMzcw.jpg       4
https://pictures-nigeria.jijistatic.net/177387742_MzAwLTQwMC02MDVjN2Q0NjU4LTE.jpg    4
                                                                                    ..
https://pictures-nigeria.jijistatic.net/166621711_MzAwLTQwMC0wZDc0M2MzZDIw.jpg       1
https://pictures-nigeria.jijistatic.net/184449797_MzAwLTQwMC1hZTNkNmQyMTkz.jpg       1
https://pictures-nigeria.jijistatic.net/129672164_MzAwLTIyNi1lZDE2ZmMyMmU5LTI.jpg    1
https://pictures-nigeria.jijistatic.net/183886490_MzAwLTI5OC1lODA0ODFhYjQ2.jpg       1
https://pictures-nigeria.jijistatic.net/184988840_MzAwLTQwMC00NzNkYmE2OGI1.jpg       1
Name: count, Length: 914, dtype: int64

## PROPERTY DESCRIPTION

In [1211]:
df_rent['property_description'].isnull().sum()

0

In [1213]:
#  Stripping out leading/trailing whitespace and also removing multiple spaces/newlines
df_rent['property_description'] = (
    df_rent['property_description']
    .astype(str)                                   
    .str.strip()                                   # remove leading/trailing spaces & \n
    .str.replace(r'\s+', ' ', regex=True)          # collapse any whitespace (spaces, \n, \t) into single space
    .replace('nan', '')                            # if any NaN became string "nan" as a result of the regular expression
    .str.strip()                                   # final strip to check and remove any white space again
    .str.lower()                                   # coverting all text to lower
)

In [1215]:
df_rent['property_description']

0       property address ajah,lekki lagos. property si...
1       property address 3bdrm bungalow inside greenla...
2       property address add.road estate name addo roa...
3       to let spaciously built 4 bedroom terrace dupl...
4       property address opic estate name isheri north...
                              ...
1355    standard lovely newly built two bedroom flat t...
1356    to let 5 bedroom maisonette with a room bq loc...
1357    to let standard luxury newly built two bedroom...
1358    standard sharp newly two bedroom terrace duple...
1359    to let standard luxury newly built miniflat up...
Name: property_description, Length: 1360, dtype: object

## PROPERTY TYPE

In [1218]:
df_rent['property_type'].isnull().sum()

0

In [1220]:
df_rent['property_type'].astype(str).unique()

array(['Duplex', 'Bungalow', 'Flat', 'Apartment', 'Terrace', 'Unknown',
       'Mansion', 'Self Contain', 'Land'], dtype=object)

In [1222]:
df_rent['property_type'].value_counts()

property_type
Duplex          580
Apartment       429
Flat            254
Terrace          27
Unknown          27
Self Contain     15
Land             14
Bungalow          8
Mansion           6
Name: count, dtype: int64

In [1226]:
unknown_count = (df_rent['property_type'] == 'Unknown').sum()
unknown_percent  = unknown_count / len(df) * 100

print(unknown_percent)

1.9852941176470587

In [1228]:
#  filling out unknown with something more formal

df_rent['property_type'] = df_rent['property_type'].replace('Unknown', 'Commercial')

In [1230]:
df_rent['property_type'].unique()

array(['Duplex', 'Bungalow', 'Flat', 'Apartment', 'Terrace', 'Commercial',
       'Mansion', 'Self Contain', 'Land'], dtype=object)

## DATES
 - #### I will be using my scraped real date **(2025-11-17 at 17:44 UTC)** as a reference to calculating and converting my dates column

In [1235]:
from datetime import datetime, timedelta
import re

SCRAPE_DATE = datetime(2025, 11, 17, 17, 44, 0)

In [1237]:
df_rent['listing_date'].isnull().sum()

0

In [1239]:
df_rent['listing_date'].unique().tolist()

['1 hour ago',
 '6 hours ago',
 '3 hours ago',
 '2 hours ago',
 '9 hours ago',
 '18 hours ago',
 '7 hours ago',
 '4 hours ago',
 '8 hours ago',
 'Unknown',
 '21 hours ago',
 '5 hours ago',
 '11 hours ago',
 '2 days ago',
 '22 hours ago',
 '10 hours ago']

In [1241]:
df_rent['listing_date'].value_counts()

listing_date
3 hours ago     510
2 hours ago     381
6 hours ago     195
7 hours ago      78
9 hours ago      74
1 hour ago       47
Unknown          36
8 hours ago      12
5 hours ago       8
10 hours ago      5
4 hours ago       4
18 hours ago      3
2 days ago        3
21 hours ago      2
11 hours ago      1
22 hours ago      1
Name: count, dtype: int64

In [1272]:
# Count "Unknown"

unknown_count = (df_rent['listing_date'] == 'Unknown').sum()
unknown_percent = unknown_count / len(df) * 100

print(f"{unknown_percent}%")

0.0%

In [1249]:
mode_value = df_rent['listing_date'].mode()[0]
mode_value

'3 hours ago'

In [1255]:
# since the missing/unknown for the listing_date is significantly small, i can then replace with the mode since it's not logical to calculate the median

print(f"Replacing the unknown values with the mode which is: {mode_value}\n")
df_rent['listing_date'] = df_rent['listing_date'].replace('Unknown', mode_value)
print("Successfully replaced the unknown with the mode")

Replacing the unknown values with the mode which is: 3 hours ago

Successfully replaced the unknown with the mode

In [1257]:
# Now time to convert to real datetime

def date_conversion_parser(text):
    if pd.isna(text):
        return pd.NaT                         # not a time
    text = str(text).lower()
    num = int(re.search(r'(\d+)', text).group(1)) if re.search(r'\d+', text) else 0
    
    if 'minute' in text or 'now' in text:  return SCRAPE_DATE
    if 'hour'   in text:  return SCRAPE_DATE - timedelta(hours=num)
    if 'day'    in text:  return SCRAPE_DATE - timedelta(days=num)
    if 'week'   in text:  return SCRAPE_DATE - timedelta(weeks=num)
    if 'month'  in text:  return SCRAPE_DATE - timedelta(days=num*30)
    if 'year'   in text:  return SCRAPE_DATE - timedelta(days=num*365)
    return SCRAPE_DATE

In [1259]:
df_rent['listing_date'] = df_rent['listing_date'].apply(date_conversion_parser)

In [1261]:
df_rent['listing_date']

0      2025-11-17 16:44:00
1      2025-11-17 11:44:00
2      2025-11-17 14:44:00
3      2025-11-17 16:44:00
4      2025-11-17 15:44:00
               ...
1355   2025-11-17 14:44:00
1356   2025-11-17 14:44:00
1357   2025-11-17 14:44:00
1358   2025-11-17 15:44:00
1359   2025-11-17 15:44:00
Name: listing_date, Length: 1360, dtype: datetime64[ns]

## LAST UPDATED

In [1266]:
df_rent['last_updated'].isnull().sum()

0

In [1268]:
df_rent['last_updated'].unique().tolist()

['1 hour ago',
 '6 hours ago',
 '3 hours ago',
 '2 hours ago',
 '9 hours ago',
 '18 hours ago',
 '7 hours ago',
 '4 hours ago',
 '8 hours ago',
 'Unknown',
 '21 hours ago',
 '5 hours ago',
 '11 hours ago',
 '2 days ago',
 '22 hours ago',
 '10 hours ago']

In [1270]:
df_rent['last_updated'].value_counts()

last_updated
3 hours ago     510
2 hours ago     381
6 hours ago     195
7 hours ago      78
9 hours ago      74
1 hour ago       47
Unknown          36
8 hours ago      12
5 hours ago       8
10 hours ago      5
4 hours ago       4
18 hours ago      3
2 days ago        3
21 hours ago      2
11 hours ago      1
22 hours ago      1
Name: count, dtype: int64

In [1274]:
# Count "Unknown"

unknown_count = (df_rent['last_updated'] == 'Unknown').sum()
unknown_percent = unknown_count / len(df) * 100

print(f"{unknown_percent}%")

2.6470588235294117%

In [1284]:
mode_value = df_rent['last_updated'].mode()[0]
mode_value

'3 hours ago'

In [1286]:
# since the missing/unknown for the listing_date is significantly small, i can then replace with the mode since it's not logical to calculate the median

print(f"Replacing the unknown values with the mode which is: {mode_value}\n")
df_rent['last_updated'] = df_rent['last_updated'].replace('Unknown', mode_value)
print("Successfully replaced the unknown with the mode")

Replacing the unknown values with the mode which is: 3 hours ago

Successfully replaced the unknown with the mode

In [1288]:
df_rent['last_updated'] = df_rent['last_updated'].apply(date_conversion_parser)

In [1290]:
df_rent['last_updated']

0      2025-11-17 16:44:00
1      2025-11-17 11:44:00
2      2025-11-17 14:44:00
3      2025-11-17 16:44:00
4      2025-11-17 15:44:00
               ...
1355   2025-11-17 14:44:00
1356   2025-11-17 14:44:00
1357   2025-11-17 14:44:00
1358   2025-11-17 15:44:00
1359   2025-11-17 15:44:00
Name: last_updated, Length: 1360, dtype: datetime64[ns]

In [1292]:
df_rent.head(1)

                      property_title    price  price_million_ngn price_readable                                  location  size_sqm  price_per_sqm                                        listing_url  bedrooms  bathrooms furnishing_status  agent_name  contact                                        image_links                               property_description property_type        listing_date        last_updated source listing_type
0  4 Bedroom Duplex in Ajah for rent  7000000               7.00         ₦7.00M  PromotedLagos, Ajah, 1 hour ago267 views    240.00          29167  https://jiji.ng/ajah/houses-apartments-for-ren...         4          4       Unfurnished  Enterprise  Unknown  https://pictures-nigeria.jijistatic.net/183052...  property address ajah,lekki lagos. property si...        Duplex 2025-11-17 16:44:00 2025-11-17 16:44:00   jiji         rent

In [1299]:
# Saving our Now Cleaned Rent in JSON Format
import os

# Path to my cleaned folder
cleaned_folder = r"Data Science Program\KWE4 STUDIO\LagosPropIQ\data\cleaned"
os.makedirs(cleaned_folder, exist_ok=True)

# Final JSON path
final_json_path = os.path.join(cleaned_folder, "rent_cleaned.json")

# Save as JSON — preserves ALL data types perfectly (Int64, datetime, etc.)
df_rent.to_json(final_json_path, orient='records', date_format='iso', force_ascii=False, indent=2)

print("="*80)
print("SALES DATA SUCCESSFULLY SAVED AS JSON!")
print("="*80)
print(f"Location : {final_json_path}")
print(f"Rows     : {len(df):,} listings")
print(f"File size: ~{os.path.getsize(final_json_path)/1024/1024:.1f} MB")

================================================================================
SALES DATA SUCCESSFULLY SAVED AS JSON!
================================================================================
Location : Data Science Program\KWE4 STUDIO\LagosPropIQ\data\cleaned\rent_cleaned.json
Rows     : 1,360 listings
File size: ~1.5 MB

# ALL DONE FOR RENT JIJI WEB SCRAPER